### ISSUE TITLE
Server returns 400 on repeated updateStructurePrediction

### ISSUE THREAD

**Issue by DanBuchan** [UCLOrengoGroup/genome3d-openapi-client#11]
Running the following repeatedly returns a 400 response from the 2nd and subsequent attempts
```
genome3d-api -o updateStructurePrediction -u Q19820 -r DomSerf --pdbfiles=sp\|A1Z8N1\|TRE11_1_174.pdb --pdbfiles=sp\|A1Z8N1\|TRE11_611_838.pdb
```
I would assume updateStructurePrediction should be successful on each attempt, updating and removing(?) the previous record. I would have thought this behaviour should be what addStructurePrediction does

**Comment by sillitoe** [comment]
Yes, thanks - this sounds like a bug.

**Comment by sillitoe** [comment]
This was a bug in the back-end that should now be solved (the main problem was that the tests were not reporting this as an error).

Thanks for reporting - please reopen if necessary.
