### ISSUE TITLE
Error while uploading the xml containing SUPERFAMILY domain annotation

### ISSUE THREAD

**Issue by arunpandu** [UCLOrengoGroup/genome3d-openapi-client#6]
Tried to upload the xml file using the below command
./genome3d-api -o updateDomainPrediction -u V5QRX7 -r SUPERFAMILY --xmlfile=../tuberculosis/V5QRX7.xml

Resulted in the following output and error message

Tue Jul 24 08:29:41 2018   INFO | APP.OPENAPI_SPEC               http://daily.genome3d.eu/api/openapi.json
Tue Jul 24 08:29:41 2018   INFO | APP.MODE                       DAILY
Tue Jul 24 08:29:41 2018   INFO | REQUEST.OPERATION              updateDomainPrediction
Tue Jul 24 08:29:41 2018   INFO | REQUEST.DATA                   {"uniprot_acc":"V5QRX7","xmlfile":[{"file":"../tuberculosis/V5QRX7.xml"}],"operation":"updateDomainPrediction","resource_id":"SUPERFAMILY"}
Tue Jul 24 08:29:41 2018   INFO | REQUEST.URL                    http://daily.genome3d.eu/api/v1/uniprot/V5QRX7/domain_prediction/SUPERFAMILY
[400] ERROR: Bad Request ({"message":"DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  permission denied for relation annotation [for Statement \"INSERT INTO annotation ( classification_node, confidence, domain_number, resource, ty...)

The input xml used is the same that was tried in issue 4
https://github.com/UCLOrengoGroup/genome3d-openapi-client/issues/4

**Comment by sillitoe** [comment]
Thanks - I can reproduce this error. 

Worked after a server restart yesterday - I think this has to be how the "daily" database is being refreshed (which happens daily at midnight).

Sorting now

**Comment by sillitoe** [comment]
As suspected, this did come down to the way the "daily" sandbox was being created.

Looks like dropping/creating a schema disrupts permissions for existing database connections (which does kind of makes sense).

Workaround involved leaving the schema in place and just dropping tables/sequences.

Tested for "daily" and "head" (before and after running the daily backup script).

More detail here:

https://dba.stackexchange.com/questions/213085/permission-errors-on-insert-after-schema-drop-create-pg-9-0-23/213105#213105
