### ISSUE TITLE
Issue with the upload 3D structural predictions

### ISSUE THREAD

**Issue by arunpandu** [UCLOrengoGroup/genome3d-openapi-client#7]
Tried to upload 3D structural model using the below command
./genome3d-api -o updateStructuralPrediction -u V5QRX7 -r SUPERFAMILY --pdbfiles=../tuberculosis/V5QRX7_4_105.pdb

Resulted in the following error:

Wed Jul 25 08:56:54 2018   INFO | APP.OPENAPI_SPEC               http://daily.genome3d.eu/api/openapi.json
Wed Jul 25 08:56:54 2018   INFO | APP.MODE                       DAILY
Wed Jul 25 08:56:54 2018   INFO | REQUEST.OPERATION              updateStructuralPrediction
Wed Jul 25 08:56:54 2018   INFO | REQUEST.DATA                   {"uniprot_acc":"V5QRX7","pdbfiles":[{"file":"../tuberculosis/V5QRX7_4_105.pdb"}],"operation":"updateStructuralPrediction","resource_id":"SUPERFAMILY"}
Can't locate object method "updateStructuralPrediction" via package "OpenAPI::Client::daily_genome3d_eu_api_openapi_json" at /data/apandura/Genome3D.2017-09-05/NEW/genome3d-openapi-client/lib/Genome3D/Api/Client.pm line 238.

Note: the github interface does not attachment of file with extension .xml and .pdb. So I am afraid I could not attach the inputs tested in the issue. I will send it through email. Thank you.

**Comment by sillitoe** [comment]
Ah - looks like you have a typo in the operation name:

updateStructur**al**Prediction -> updateStructur**e**Prediction

It's a pretty ugly error message though - the changes in af53fc93c736b15f47bdb61310ed2d5558c582da should make this a bit more obvious.

Providing an unknown operation name should now print something along the lines of:

```
ERROR: 'updateStructuralPrediction' is not a valid operation name (use --list to provide a list of available operations)
```
